### ISSUE TITLE
v1.3.0 Roadmap - 开发路线图

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/electronic-wechat#165]
- [x] `关键` - 优化应用基础体验，重点优化登录体验
 - [x] `关键` - 修复已知的 blocking bugs
 - [ ] `重要` - 重构代码，以期在微信代码变动时实现功能优雅降级
 - [x] `一般` - 验证应用在不同 Linux 发行版的跨平台兼容性 `Help Wanted`
 - [x] `一般` - 增加用户建议的新功能 `Help Wanted`

我创建了一个 [系统支持矩阵 Wiki](https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix) ，面对所有社区用户开放。一个人的精力总是有限的，希望大家共同参与到 **操作系统支持矩阵** 的维护，协助验证 Electronic WeChat 在不同 Linux 发行版下的兼容性问题。

**Comment by mengzyou** [comment]
我使用的是openSUSE KDE桌面，可以验证在openSUSE上的平台兼容性

**Comment by geeeeeeeeek** [comment]
@mengzyou 非常感谢！我创建了一个 [系统支持矩阵 Wiki](https://github.com/geeeeeeeeek/electronic-wechat/wiki/System-Support-Matrix) ，欢迎你验证后添加。

**Comment by mengzyou** [comment]
@geeeeeeeeek 好的，不过对于wiki，我还不是很清楚怎么编辑，是需要clone下来，然后push吗？还是我在这里向report？

**Comment by geeeeeeeeek** [comment]
@mengzyou 不需要，右上角you有一个 Edit 按钮，可以在页面上编辑。不过需要了解一些 Markdown 的语法，你可以照着其他 row 写。

![image](https://cloud.githubusercontent.com/assets/7262715/15010737/39524272-1220-11e6-8bb7-ad8b3a43b7d0.png)

**Comment by mengzyou** [comment]
@geeeeeeeeek 咦，我没看到有`Edit`的按钮啊，是不是没有权限啊？  
![screenshot_20160504_175109](https://cloud.githubusercontent.com/assets/360603/15010868/1bc22d3e-1221-11e6-8b20-acbb66bbc5a8.png)

**Comment by geeeeeeeeek** [comment]
@mengzyou 不好意思，之前是设置问题，现在应该可以了
